### ISSUE TITLE
Method In can't accept a slice

### ISSUE THREAD

**Issue by petersunbag** [huandu/go-sqlbuilder#1]
``` 
// In represents "field IN (value...)".  
func (c *Cond) In(field string, value ...interface{}) string {
```

```
func GetByIds(ids []int64) (err error) {
	sb :=sqlbuilder.NewSelectBuilder()
	sb.Select("*")
	sb.From(tableName)
	sb.Where(
		sb.In("delivery_id", deliveryIds...),
	)
```
make error is
> cannot use deliveryIds (type []int64) as type []interface {} in argument to sb.Cond.In

It seems the only way is to do a for-loop to transfer the deliveryIds to a []interface {}, but it is ugly.
Maybe method In can the do this transfer.

**Comment by huandu** [comment]
Provide a function [Flatten](https://godoc.org/github.com/huandu/go-sqlbuilder#Flatten) now.

Usage:

```go
ids := []int64{1, 2, 3}
sb.Where(
    sb.In("id", sqlbuilder.Flatten(ids)...),
)
```
