### ISSUE TITLE
SQL Exists operator

### ISSUE THREAD

**Issue by diegosogari** [huandu/go-sqlbuilder#100]
I didn't find a `builder.Exists()` method in the codebase. Is there a way to accomplish this?

**Comment by doyonghoon** [comment]
Hey, I hope the following suggestion may help.

An ultimate function to generate whatever the query you'd like to have is using `SQL(raw_sql string)`. Examples are found in the following link: https://pkg.go.dev/github.com/huandu/go-sqlbuilder#SelectBuilder.SQL

**Comment by huandu** [comment]
I plan to support `EXISTS`, `NOT EXISTS`, `ANY`, `SOME` and `ALL` in builders which have `WHERE` clause. I'll finish it in this weekend.

Before that, you can simply write code like following.

```go
sb := sqlbuilder.Select("col").From("table1")
subquery := sqlbuilder.Select("1").From("table2").Where("status = 1")

// Use sb.Var() and Buildf to build EXISTS clause.
sb.Where(
    sb.Var(sqlbuilder.Buildf("EXISTS(%v)", subquery)),
)

println(sb.String())

// Output:
// SELECT col FROM table1 WHERE EXISTS(SELECT 1 FROM table2 WHERE status = 1)
```
