### ISSUE TITLE
LastInsertId is not supported by this driver

### ISSUE THREAD

**Issue by vedtra** [huandu/go-sqlbuilder#103]
func CreateNewNews(tx *sql.Tx, p interface{}) (result sql.Result, err error) {

	sb := sqlbuilder.PostgreSQL.NewInsertBuilder()
	sb.InsertInto(model.TableCampaigns)
	sb.Cols(
		"name",
	)
	sb.Values(
		p,
	)
	sb.SQL("RETURNING id")
	sqlStatement, args := sb.Build()
	fmt.Print("sql", sqlStatement)
	fmt.Print("args", args)

	stmt, err := tx.Prepare(sqlStatement)
	if err != nil {
		return nil, database.Error(err)
	}

	result, err = stmt.Exec(args...)
	fmt.Printf("pass")
	fmt.Print(result.LastInsertId())
	err = database.Error(err)

	return
}
`
result.LastInsertId() always return 0, case postgres

**Comment by huandu** [comment]
PostgreSQL driver doesn't return the last insert id through `result.LastInsertId()`. Instead, it returns the id in row.

```go
var id int64
err = stmt.QueryRow(args...).Scan(&id)
```

This behavior is a feature in PostgreSQL driver (most likely `github.com/lib/pq`), not this package.
