### ISSUE TITLE
like '%?%'

### ISSUE THREAD

**Issue by anatoly-ex** [huandu/go-sqlbuilder#105]
if one needs the following sql
```sql
select * from t where c like '%?%'
```
(or any other `like` pattern where the `?` value(s) is(are) get from a variable(s) and therefore has to be properly escaped, e.g. `like '? + ? = ?'`) - how do they do it with `sqlbuilder`? it turns out they cannot just use the (specifically intended for `like` conditions) `Cond.Like` since it requires the condition to be `like ?` and not any other string. the only option is to use a combination of `Raw` and `Cond.Var`? are you going add such a feature any time soon? maybe something like `Expr` in `squirrel`?

or maybe i'm getting it wrong? what is the correct way to achieve this with `sqlbuilder`?

### UPD.
hmm... it seems to me, the question is even wider: how does one supply their own custom expressions instead of direct values when using `Cond`itions? i.e. a way to use `Cond.Like` in conjunction with `Var`, e.g. instead of literally specifying the `like` in sql like this:
```go
sb.Where("tbl.fld like concat('%', " + sb.Var(myVar) + ", '%')")
```
intead of this, how to specify it in conjunction with `Cond.Like` like this:
```go
sb.Where(sb.Like("tbl.fld", sb.Expr("concat('%', " + sb.Var(myVar) + ", '%')"))
```

### UPD2.
e.g. here's how i achieved this with my custom code:
```go
func LikeExpr(field string, expr string) string {
	buf := &strings.Builder{}
	buf.WriteString(sqlbuilder.Escape(field))
	buf.WriteString(" LIKE ")
	buf.WriteString(expr)
	return buf.String()
}

sb.Where(LikeExpr("tbl.fld", "concat('%', "+sb.Var(myVar)+", '%')"))
```
\- but i think this lib needs some generalized solution so that users don't have to write their custom code for each `Cond`, what do you think?

**Comment by huandu** [comment]
I think you can use following code to escape `myVar`.

```go
sb.Where(sb.Like("tbl.fld", "%"+myVar+"%")
```

I'm not sure why you have to build SQL `LIKE concat('%', ?, '%')` instead of `LIKE ?`. There should be no different in these two forms. Is there any specific reason that you cannot use `LIKE ?` in your case?

**Comment by huandu** [comment]
Close it as there is no more discussion for two weeks. Feel free to re-open it if you still have any issue.
