### ISSUE TITLE
Global insert builder?

### ISSUE THREAD

**Issue by vedtra** [huandu/go-sqlbuilder#106]
`var ib = sqlbuilder.PostgreSQL.NewInsertBuilder()

func insert() {
  ib.InsertInto(users)   // first insert
  .....
   ....
  ib.InsertInto(detail_users) // second insert
  ....
  ....
}
`
first insert succes insert data but second failed,how to make ib global?

**Comment by huandu** [comment]
The builder should not be a global variable. It's not thread-safe. You should create a new builder to build a SQL and then abandon it.

If you're looking for a way to reuse some parts of a builder, you can have two choices.

- Consider [`Struct`](https://pkg.go.dev/github.com/huandu/go-sqlbuilder#Struct) and related APIs. You can read the doc and samples to understand whether it can be useful in your case.
- Or, you can write a factory function to create an `InsertBuilder` and initialize it.

**Comment by vedtra** [comment]
thak you for your explanation
