### ISSUE TITLE
why builders do not implement same interface for most methods

### ISSUE THREAD

**Issue by farmani** [huandu/go-sqlbuilder#107]
I'm not sure if I should categorize this as a question or suggestion.

I'm trying to create a set of query builder on top of your package to have a set of chain-able methods but because of having multiple query builder type they cannot be reusable. problem is in defining DeleteBuilder / SelectBuilder and etc

I believe at least must implement same interface like Builder (or extend Builder interface with more methods like Where() and etc)

this way someone can write reusable/chain-able method like

```go
func (qb *QueryBuilder) GetById(id uint64) *QueryBuilder {
	qb.Where(qb.Equal("id", id))
	return qb
}

func (qb *QueryBuilder) Active() *QueryBuilder {
	qb.Where(qb.Equal("statys", "active"))
	return qb
}

func (qb *QueryBuilder) One(c echo.Context) *sql.Row {
	// return row
}

func (qb *QueryBuilder) Delete(c echo.Context) error {
	// ..
}
```

now someone can use it this way

```go
qb.GetById(id).Active().One()
// or
qb.GetById(id).Active().Delete()
```

anyway I really look for such query builder and try many available package non of them do the job completely without lots of overhead or bolted code. your package was the best so far the only problem to me was this, probably there was a reason to define multiple builder type but finally they are same thing (use to create query condition) so chain-able pattern make them a lot more reusable for developers.

**Comment by huandu** [comment]
I can show you one possible solution based on generic, which is supported by Go 1.18+.

Suppose we have a type called `WhereClause` holding necessary parameters to build WHERE clause. We can define it like following.

```go
type WhereClause[T any] struct {
	super *T // The real type returned in all chain-able methods.

	andExpr []string
}

func NewWhereClause[T any](super *T) *WhereClause[T] {
	return &WhereClause[T]{
		super: super,
	}
}

func (wc *WhereClause[T]) Where(andExpr ...string) *T {
	wc.andExpr = append(wc.andExpr, andExpr...)
	return wc.super
}

func (wc *WhereClause[T]) newSelectBuilder() *sqlbuilder.SelectBuilder {
	return sqlbuilder.NewSelectBuilder().Where(wc.andExpr...)
}

func (wc *WhereClause[T]) newDeleteBuilder() *sqlbuilder.DeleteBuilder {
	return sqlbuilder.NewDeleteBuilder().Where(wc.andExpr...)
}
```

When we use this type in a query builder, we can implement it like following.

```go
type QueryBuilder struct {
	*WhereClause[QueryBuilder]
	sqlbuilder.Cond
}

func NewQueryBuilder() *QueryBuilder {
	qb := &QueryBuilder{}
	qb.WhereClause = NewWhereClause(qb)
	qb.Cond.Args = &sqlbuilder.Args{}
	return qb
}

func (qb *QueryBuilder) One() (row *sql.Row) {
	sb := qb.newSelectBuilder()
	*sb.Args = *qb.Args // Transfer all stored arguments to builder.

	// Initialize the sb with necessary information.
	sb.Select("foo").From("table")

	// Build SQL and execute it.
	sql, args := sb.Build()
	fmt.Println(sql, args)

	// row = ...
	return
}

func (qb *QueryBuilder) Delete() (row *sql.Row) {
	db := qb.newDeleteBuilder()
	*db.Args = *qb.Args // Transfer all stored arguments to builder.

	// Initialize the sb with necessary information.
	db.DeleteFrom("table")

	// Build SQL and execute it.
	sql, args := db.Build()
	fmt.Println(sql, args)

	// row = ...
	return
}
```

As a result, `QueryBuilder` methods, especially the `Where` method, can return `*QueryBuilder`.

```go
qb1 := NewQueryBuilder()
qb1.Where(
    "a = b + c",
    qb1.Like("name", "%foo"),
).One()

qb2 := NewQueryBuilder()
qb2.Where(qb2.In("status", 1, 2, 3)).Delete()
```

You can review [the full sample](https://go.dev/play/p/bjZL-TmODQ2) in Go playground. Have fun!

**Comment by huandu** [comment]
Go generic is still immature and evolving. That's why I doubt to use it in production.

One suggestion for your sample code. I think `QueryBuilder` should not hold a builder instance. If `QueryBuilder` holds a select builder, this builder cannot be used to build DELETE statement in `Delete()`.

**Comment by huandu** [comment]
Close it due to no more comments for a week. Feel free to re-open it if you have more thoughts to discuss.
