### ISSUE TITLE
Gin Query Params as filter

### ISSUE THREAD

**Issue by boskiv** [huandu/go-sqlbuilder#109]
I there a general and minimal solution to convert gin query params to sqlbuilder WHERE filter?

I have 
```
type MessageParams struct {
  StartTime int64
  EndTime   int64
  Symbol    string
  Volume    float64
  Page      int
  Limit     int
  IsDesc    bool
}
...
var messageParams MessageParams
c.ShouldBindQuery(&messageParams)
```

I want to build an SQL query regarding params that exist in the structure.
Is there a more convenient way except multiple if's ?
Only I can get is
```
if(message.Limit > 0) {
sb.Where(sb.eq("limit", limit))
    }
    e.t.c
```
Maybe there is an external package that exists to figure it out? I have had no success yet finding it GitHub :(

**Comment by huandu** [comment]
I don't know any package to fit your requirement. However, it seems to be a quite useful feature. I'll try to implement it in this package.

**Comment by huandu** [comment]
@boskiv After I try to design new APIs for this feature, I fail to find a design which is clear enough and can be called with only a few lines of code. I think using `if` is good enough in your case. So I'll close this issue as "won't fix". If you have any idea, feel free to add your comment in this issue.
