### ISSUE TITLE
Limit By not supported

### ISSUE THREAD

**Issue by astudnev** [huandu/go-sqlbuilder#110]
There is no good way to include "limit by " clause in query

https://clickhouse.com/docs/en/sql-reference/statements/select/limit-by

**Comment by huandu** [comment]
AFAIK, `LIMIT BY` is a Clickhouse-only SQL extension. It's not feasible to add a new method `LimitBy` in `SelectBuilder` as it's not possible to build runnable SQL for all flavors.

My recommendation is to use the `SQL()` method to build `LIMIT BY` manually.

**Comment by huandu** [comment]
Close this issue as it's out-of-scope of this package. I recommend to use `SQL()` to build such clause.
