### ISSUE TITLE
WHERE clause is always taking AND condition. No way to support OR condition

### ISSUE THREAD

**Issue by vigneshvn1995** [huandu/go-sqlbuilder#113]
Is there anyway I can achieve this?
SELECT column1, column2, FROM table_name WHERE condition1 OR condition2 OR condition3

**Comment by huandu** [comment]
You can try to use [`Or(orExpr ...string)`](https://pkg.go.dev/github.com/huandu/go-sqlbuilder#Cond.Or). It's available in all builders having `WHERE`.

```go
sb := sqlbuilder.Select("foo").From("bar")
sb.Where(
    sb.Or(
        sb.Eq("a", 1),
        sb.In("b", 1, 2, 3),
    ),
)
```

**Comment by vigneshvn1995** [comment]
Yes I got it but if we have a combination of AND and OR with the where clause, I think we are not able to do it
ex: SELECT column1, column2 FROM table_name WHERE condition1 AND condition2 OR condition3

sb := sqlbuilder.Select("column1", "column2 ").From("table_name ")
sb.Where(sb.eq("key1",value1))
sb.Where(sb.OR(sb.eq("key2",value2))

SQL statement for this will be:- SELECT column1, column2 FROM table_name WHERE condition1 AND condition2 AND (condition3)
Here as soon I use Where clause it uses AND, but if I need OR AND both, how can I use 
Please let me know if there is a way to achieve this

**Comment by huandu** [comment]
I see. There is no way to build SQL `cond1 AND cond2 OR cond3` with this package. However, it's possible to build `((cond1 AND cond2) OR cond3)`, which works exactly the same as the expected SQL.

```go
sb.Where(
    sb.Or(
        sb.And(
            sb.E("key1", value1),
            sb.E("key2", value2),
        ),
        sb.E("key3", value3),
    ),
)
```

**Comment by huandu** [comment]
Close it as no follow-ups for months.
