### ISSUE TITLE
Is there a way to parse existing sql queries into sqlbuilder and then add more on top of the parsed query?

### ISSUE THREAD

**Issue by vamshiaruru32** [huandu/go-sqlbuilder#115]
For example, let us say I have a query like "SELECT id, name, slug FROM product" which I am already using in my code else where. Now I want to add more conditions on top of that using sqlbuilder. Is there a way to parse this into a select statement? I have tried the following
```go
	sb := sqlbuilder.NewSelectBuilder()
	sb.SQL(query).Where(
		sb.In("id", 1, 2, 3),
	)
	q, args = sb.Build()
	fmt.Println(q, args)
```
But this prints
```
SELECT id, name, slug FROM page SELECT  FROM  WHERE id IN (?, ?, ?) [1 2 3]
```
With an extra select from. Is this a valid usecase for this library?

Thanks for any help, the library seems awesome!

**Comment by huandu** [comment]
There is no such feature right now. I'm considering how to support it. One possible design is that: When building a SQL, Builders ignore all parts which is not set.

For instance, if we don't call `Select` and `From` on a `SelectBuilder`, the `SELECT` and `FROM` clause are completely missing in the final output.

**Comment by vamshiaruru32** [comment]
Thanks, that sounds useful. one very useful thing this unlocks is being able to use this sqlc. Use sqlc to generate models from a query, and add dynamic where and pagination clauses using this library.
