### ISSUE TITLE
是否可以支持oracle?

### ISSUE THREAD

**Issue by zhangyongding** [huandu/go-sqlbuilder#118]
请问下一个版本可以支持oracle吗？

**Comment by huandu** [comment]
我没用过 Oracle，也没有测试环境，我了解到 Oracle SQL 语法比较特别，所以可能困难有点大。你能提供一些资料给我么，让我知道 Oracle SQL 跟标准 ISO SQL 差别有多大，这样我就能评估一下是否可以支持了。

**Comment by zhangyongding** [comment]
我也没有更多的资料
oracle的软件可以通过oracle的官网下载：https://www.oracle.com/cn/downloads/

**Comment by zhangyongding** [comment]
我准备尝试自己fork，到时候提交一个pr，希望能合并

**Comment by zhangyongding** [comment]
提交了一个支持oracle的pr， #126 ，看是否可以合并

**Comment by huandu** [comment]
多谢，我会看一下。最近我非常的忙，可能得晚一些到九月底才能看完这个 PR，到时候我们在 PR 中交流。
