### ISSUE TITLE
自定义dbtag

### ISSUE THREAD

**Issue by zhangyongding** [huandu/go-sqlbuilder#119]
是否可以在dbtag有值的时候，也调用FieldMapperFunc，以便于可以自定义dbtag的内容？

**Comment by zhangyongding** [comment]
提交了一个PR: https://github.com/huandu/go-sqlbuilder/pull/120

**Comment by huandu** [comment]
之前的逻辑是，DBTag 的优先级高于 mapper，一旦写了就不会受到 mapper 影响，这是为了允许使用者用 mapper 解决大部分通用问题（比如转小写下划线风格字段名、或者给字段统一加一个前缀），特殊情况则用 `db:"xxx"` 来进行覆盖。如果按照你的 PR 的改法，这种场景就无法满足了，所以我不能合并你的 PR 代码。

我不知道你的使用场景是什么，希望能描述一下，我看应该怎么设计比较好。

**Comment by zhangyongding** [comment]
我希望是通过DBTag定义一些Create Table的属性，用于创建表，我参考了其他的orm的做法，都有类似的功能，例如：gorm和xorm

**Comment by zhangyongding** [comment]
提交了新的PR，请审核一下 #121
