### ISSUE TITLE
Add Query Cache

### ISSUE THREAD

**Issue by iambudi** [huandu/go-sqlbuilder#122]
Is it possible to add a cache feature for generated queries with a fixed number of parameters, where only the argument value changes, while the rest of the query remains intact? I don't do benchmark yet, but rebuilding query seems a bit expensive.

Do you have a plan or should we just create tiny wrapper on top of the sqlbuilder to handle that?

**Comment by huandu** [comment]
Generally speaking, it's not necessary to implement a cache. This package performs really good. Building a SQL will only cost < 1μs. You can read #94 for details.

If you need a kind of string template, you can use [Build](https://pkg.go.dev/github.com/huandu/go-sqlbuilder#Build) or [BuildNamed](https://pkg.go.dev/github.com/huandu/go-sqlbuilder#BuildNamed).

**Comment by iambudi** [comment]
The benchmark seems a simple one. Considering structfield using reflection which can introduce performance overhead and slow down code execution.

Thanks for suggesting BuildNamed.

**Comment by huandu** [comment]
The reflect package is only used for the first time parsing a struct. After that, all `Struct` methods and all kinds of builders just simply concat strings without calling any reflect method. You can read source code for details.
