### ISSUE TITLE
Question: Proper method to reuse query

### ISSUE THREAD

**Issue by iambudi** [huandu/go-sqlbuilder#123]
When doing select query with complex filtering to list data with pagination, is there a recommended way to reuse FROM and WHERE condition from single SelectBuilder.

getting rows from sb.build()
```SELECT (cols) FROM (table & JOIN) WHERE (filtering here) LIMIT 10 OFFSET 10```

getting total of filtered rows, can we reuse sb without the LIMIT/OFFSET part and replace the (cols) with COUNT(*).
```SELECT COUNT(*) FROM (table & JOIN) WHERE (filtering here)```

Thank you

**Comment by iambudi** [comment]
To illustrate, currently i do in the reverse order with sb copy
```go
// Here no field to select yet
cb := sqlbuilder.NewSelectBuilder()
cb.From("my_table").
Where(
	sb.Equal("cond1", "1"),
	sb.Equal("cond2", "2"),
)

sb := cb // reuse condition of count builder to sb
sb.Select("col1, col2, col3").Limit(10).Offset(10)
cb.Select("COUNT(*) AS total_rows") 
```

**Comment by huandu** [comment]
In general, it's not recommended to cache build instances, as they are stateful. If you want to reuse code, it's recommended to write a factory method to return a initialized builder instance. You don't need to worry about performance issue a lot. This package has tried to keep extra overhead as low as possible.

```go
func NewMyTableBuilder() *sqlbuilder.SelectBuilder {
    sb := sqlbuilder.NewSelectBuilder()
    sb.From("my_table").
    Where(
	    sb.Equal("cond1", "1"),
	    sb.Equal("cond2", "2"),
    )
    return cb
}

sb := NewMyTableBuilder().Limit(10).Offset(10)
```
