### ISSUE TITLE
How about add a Pair to Insert statement?

### ISSUE THREAD

**Issue by donnol** [huandu/go-sqlbuilder#124]
Something like:

```go
// Signature
func  Pair(column string, values ...any) 

// insert into table (column_name, column_name_2) values (columnValue, columnValue2);
insertStatement := sqlbuilder.NewInsertBuilder().InsertInto("table").Pair("column_name", columnValue).Pair("column_name_2", columnValue2)

// insert into table (column_name, column_name_2) values (columnValue, columnValue2), (columnValue11, columnValue22);
insertStatement := sqlbuilder.NewInsertBuilder().InsertInto("table").Pair("column_name", columnValue, columnValue11).Pair("column_name_2", columnValue2, columnValue22);
```

**Comment by huandu** [comment]
In this package, one design principle is to maintain semantic consistency between Go statements and the SQL generated by these statements. That means, if we read Go code `InsertInto("table").Cols("a", "b").Values(1, 2)`, then we can expect to get `INSERT INTO table ("a", "b") VALUES (?, ?)`, which is an almost 1:1 translation from Go statements. Thus, the `Pair` method, though it's convenient in some cases, is not intuitive enough.

I recommend you to wrap a new builder on top of `InsertBuilder` to add the `Pair` method, if you really need this.

**Comment by donnol** [comment]
Ok, thanks.
