### ISSUE TITLE
How to use builder with equality

### ISSUE THREAD

**Issue by cemremengu** [huandu/go-sqlbuilder#128]
I am trying to use the result of a subquery in an equality but could not figure out how to do it. 

Trying something like below, any ideas how to achieve this?

```
someId := 1 // this is coming from the function parameter
sub := sqlb.NewSelectBuilder()
sub.Select("module_id").From("fault.alarm").Where(sub.EQ("id", someId)).Limit(1)


sb := sqlb.NewSelectBuilder()
sb.Where(
    sb.EQ("id", sb.Var(sub))
)
```

**Comment by huandu** [comment]
Here is a sample for you.

https://go.dev/play/p/QCnytMo9jzl

```go
someId := 1 // this is coming from the function parameter
sub := sqlbuilder.Select("module_id").From("fault.alarm")
sub.Where(sub.E("id", someId)).Limit(1)

sb := sqlbuilder.Select("foo")
sb.Where(sb.In("id", sub))
```

P.S. MySQL doesn't support sub query with `LIMIT` clause.

**Comment by cemremengu** [comment]
Thanks so much! For the performance implications, and I think the optimizer will convert `IN` with a single value to `=` so they are basically the same
