### ISSUE TITLE
该包如何强制设置索引？

### ISSUE THREAD

**Issue by Xuzming-996** [huandu/go-sqlbuilder#130]
如题，我想强制使用某个索引构建Sql,该如何做

**Comment by huandu** [comment]
不太明白，能举个例子么？这个库只是用来拼接 SQL 字符串的，不具有 ORM 框架的建表或者 SELECT 时候自动指定索引的能力，不过你可以说一下你的需求，我看看是否能有什么方法来帮助你。

**Comment by Xuzming-996** [comment]
按我的理解是如果只是构建出来的sql语句，*SelectBuilder结构能否添加一个强制使用索引的方法呢？具体的语法为select * from table force index(column) where column = xxx。具体的强制使用索引是否成功倒不用关心，由mysql执行时做判断就好。只是需要一个构建该类型语句的一个方法

**Comment by huandu** [comment]
你可以这样写。

```go
sb := sqlbuilder.Select("*").From("table")

// 在 From 之后调用 SQL 就可以插入自定义的语句。
sb.SQL("FORCE INDEX(column)")

// 继续正常的调用 Where。
sb.Where(sb.Equal("column", 123))
```

**Comment by Xuzming-996** [comment]
> 你可以这样写。
> 
> ```go
> sb := sqlbuilder.Select("*").From("table")
> 
> // 在 From 之后调用 SQL 就可以插入自定义的语句。
> sb.SQL("FORCE INDEX(column)")
> 
> // 继续正常的调用 Where。
> sb.Where(sb.Equal("column", 123))
> ```

好的，感谢指导！
