### ISSUE TITLE
Insert with subselect

### ISSUE THREAD

**Issue by cemremengu** [huandu/go-sqlbuilder#132]
What is a good way to implement insert with a select statement? 

I create a select builder and then set it inside the insert builder. Trying something like below when building insert:

```
if ib.sb != nil {
	query, args := ib.sb.Build()
	buf.WriteString(" (")
	buf.WriteString(query)
	buf.WriteString(")")
	println(buf.String())
	initialArg = append(initialArg. args...)
	return ib.args.Compile(buf.String(), initialArg...)
}
```

However, I am unable to get the args correctly. Somehow placeholders are missing from the final output. Any suggestions?

**Comment by huandu** [comment]
You can call `ib.args.Add(sb)` to get a placeholder string holding a reference to `SelectBuilder` instance. You can then use the placeholder string 

Here is a reference implementation for a `INSERT INTO ... SELECT` builder: https://go.dev/play/p/sWHptqfluAS

**Comment by cemremengu** [comment]
Thanks this worked like a charm! Would you like me to send a PR for this?

**Comment by huandu** [comment]
Yes, it's appreciated. Regarding to the `INSERT INTO ... SELECT` design, it's recommended to extend `InsertBuilder` rather than add a new builder. We can discuss more details in your PR.
