### ISSUE TITLE
您好，请教一个关于条件拼接的问题

### ISSUE THREAD

**Issue by ochipe** [huandu/go-sqlbuilder#135]
```
c := sqlbuilder.Cond{}
 q := c.Or(
  c.And(
   c.E("key1", 1),
   c.E("key2", 1),
  ),
  c.E("key3", 1),
 )

 builder := m.DeleteBuilder()
 builder.From(m.table)
 builder.Where(q)
```
如上面所示。其中 sqlbuilder.Cond{} 我想作为条件拼接的初始化，然后下面 and  or都是拼接具体条件，下面是把条件放到具体操作中，但是这种总觉得不是很好，能否作者留一个联系方式，想请教下这个问题

**Comment by huandu** [comment]
`Cond` 的各种函数返回值是不能用来复用，通过这段代码得到的 `q` 虽然看起来似乎可以放到 `Where` 里面，但实际上不能正常工作，`q` 里面的 `$0` `$1` 是引用的 `c` 里面存储的变量，如果直接把 `q` 传入 `builder.Where()` 里面，那么引用的变量就会错误的引用 `builder` 里面的变量，肯定就错误了。

比较推荐的做法是写一个函数，将 `builder` 传进来，函数里面封装重复的业务逻辑。

例如你的例子里面，比较推荐实现一个这样的函数：

```go
func SomeCond(c *sqlbuilder.Cond) string {
	return c.Or(
		c.And(
			c.E("key1", 1),
			c.E("key2", 1),
		),
		c.E("key3", 1),
	)
}

builder := sqlbuilder.DeleteFrom("foo")
builder.Where(SomeCond(&builder.Cond))
```

**Comment by ochipe** [comment]
> `Cond` 的各种函数返回值是不能用来复用，通过这段代码得到的 `q` 虽然看起来似乎可以放到 `Where` 里面，但实际上不能正常工作，`q` 里面的 `$0` `$1` 是引用的 `c` 里面存储的变量，如果直接把 `q` 传入 `builder.Where()` 里面，那么引用的变量就会错误的引用 `builder` 里面的变量，肯定就错误了。
> 
> 比较推荐的做法是写一个函数，将 `builder` 传进来，函数里面封装重复的业务逻辑。
> 
> 例如你的例子里面，比较推荐实现一个这样的函数：
> 
> ```go
> func SomeCond(c *sqlbuilder.Cond) string {
> 	return c.Or(
> 		c.And(
> 			c.E("key1", 1),
> 			c.E("key2", 1),
> 		),
> 		c.E("key3", 1),
> 	)
> }
> 
> builder := sqlbuilder.DeleteFrom("foo")
> builder.Where(SomeCond(&builder.Cond))
> ```

@huandu. 这种写法似乎在一些场景有问题，比如这种场景, a表，b表，c表中都有字段user_id,我想通过user_id这个条件来删除数据，查询条件拼接转为为sql：
```
  user_id = 1 and status = 1;
```

那这个条件我复用有什么好的办法，其中对a表，b表，c表三个表的操作是不同的三个函数，上层做了一个聚合，在聚合中准备把这个查询 条件传递下去

**Comment by ochipe** [comment]
@huandu 嗯，我还是函数参数操作 类型，比如updatebuild,然后聚合的时候先 把条件组合好，每个都用，然后传递下去的时候builder.Where(SomeCond(&builder.Cond)) 这样处理下，可否加您一个联系方式，微信或者其他的

**Comment by xhochipe** [comment]
> `Cond` 的各种函数返回值是不能用来复用，通过这段代码得到的 `q` 虽然看起来似乎可以放到 `Where` 里面，但实际上不能正常工作，`q` 里面的 `$0` `$1` 是引用的 `c` 里面存储的变量，如果直接把 `q` 传入 `builder.Where()` 里面，那么引用的变量就会错误的引用 `builder` 里面的变量，肯定就错误了。
> 
> 比较推荐的做法是写一个函数，将 `builder` 传进来，函数里面封装重复的业务逻辑。
> 
> 例如你的例子里面，比较推荐实现一个这样的函数：
> 
> ```go
> func SomeCond(c *sqlbuilder.Cond) string {
> 	return c.Or(
> 		c.And(
> 			c.E("key1", 1),
> 			c.E("key2", 1),
> 		),
> 		c.E("key3", 1),
> 	)
> }
> 
> builder := sqlbuilder.DeleteFrom("foo")
> builder.Where(SomeCond(&builder.Cond))
> ```

对于变长的参数这种怎么拼接比较好，比如查询一个列表，好多条件，这时候按照合理的条件来拼接这个条件比较合理优雅
