### ISSUE TITLE
`Cond` 拼接变长不固定查询参数，怎么处理

### ISSUE THREAD

**Issue by xhochipe** [huandu/go-sqlbuilder#136]
`Cond` 的各种函数返回值是不能用来复用，通过这段代码得到的 `q` 虽然看起来似乎可以放到 `Where` 里面，但实际上不能正常工作，`q` 里面的 `$0` `$1` 是引用的 `c` 里面存储的变量，如果直接把 `q` 传入 `builder.Where()` 里面，那么引用的变量就会错误的引用 `builder` 里面的变量，肯定就错误了。

比较推荐的做法是写一个函数，将 `builder` 传进来，函数里面封装重复的业务逻辑。

例如你的例子里面，比较推荐实现一个这样的函数：

```go
func SomeCond(c *sqlbuilder.Cond) string {
	return c.Or(
		c.And(
			c.E("key1", 1),
			c.E("key2", 1),
		),
		c.E("key3", 1),
	)
}

builder := sqlbuilder.DeleteFrom("foo")
builder.Where(SomeCond(&builder.Cond))
```

_Originally posted by @huandu in https://github.com/huandu/go-sqlbuilder/issues/135#issuecomment-1850216255_
            
比如现在查询列表，根据不同情况拼接不同的cond条件，这时候怎么比较优雅的处理

**Comment by huandu** [comment]
不太明白你最纠结的点是什么。按照当前的设计，`Cond` 里面的方法大部分返回的都是普通的字符串，如果你需要拼接一堆的 `AND` 条件，最简单的模式就是弄一个 `andExprs []string`，不断的将 `c.E()` 和 类似函数的返回值 `append` 进去，最后调用 `C.And(...andExprs)` 生成一个完整的 `AND` 表达式。如果同时还融合 `OR` 也可以用类似方法处理，毕竟最后拼出来的表达式一定会放入一个 `c.And` 或者 `c.Or` 拼接出最终的条件。

你可以多举一些具体的业务场景，这样我才能理解你到底在纠结什么。
