### ISSUE TITLE
Subquery in SELECT columns

### ISSUE THREAD

**Issue by umalmyha** [huandu/go-sqlbuilder#138]
Hi,

I want to construct PostgreSQL query below using `SelectBuilder` but, unfortunately, can't find a good options for that:

```sql
SELECT
  id,
  status,
  created_by,
  created_at,
  ARRAY(
    SELECT row(number, order_id, status)
    FROM order_items
    WHERE order_items.order_id = orders.id AND order_items.status = $1
  )
FROM orders
WHERE orders.status = $2
```

`SelectBuilder`'s method `Select` accepts strings as argument and I don't see workaround which is good enough to construct query above. Do you probably have some suggestion or it might be a candidate for new feature?

**Comment by huandu** [comment]
You can use `sb.Var()` to embed any builder in `sb.Select()`. I can demonstrate it in following sample ([live demo](https://go.dev/play/p/4P1-UJfIVou)).

```go
func main() {
	itemStatus := 1
	orderStatus := 2

	subQuery := sqlbuilder.Select("row(number, order_id, status)").From("order_items")
	subQuery.Where(
		"order_items.order_id = orders.id",
		subQuery.Equal("order_items.status", itemStatus),
	)

	sb := sqlbuilder.NewSelectBuilder()
	sb.Select(
		"id",
		"status",
		"created_by",
		"created_at",
		"ARRAY("+sb.Var(subQuery)+")",
	).
		From("orders").
		Where(sb.Equal("orders.status", orderStatus))

	sql, args := sb.BuildWithFlavor(sqlbuilder.PostgreSQL)
	fmt.Println(sql)
	fmt.Println(args)
}
```

**Comment by umalmyha** [comment]
Thanks a lot! Silly me, just didn't notice this nice option!
