### ISSUE TITLE
Can we parse plain text sql queries and get sqlbuilder object ?

### ISSUE THREAD

**Issue by Adeesh2411** [huandu/go-sqlbuilder#141]
I have an existing sql query in plain text format, I want to update this or add extra condition on top it. 
Like lets says we have query called : 
`select name, address, phone from userinfo group by name` 

This query I have it in plain text format, I want `sqlbuilder` object  by parsing above query. 
Then at run time, I will keep updating the where clause by calling `sb.Where()`, and this would generate correct sql query. 

There `sb.SQL()`, which takes in sql content and returns sqlbuilder, But this doesn't parse the query. And when I add `sb.Where()`, it just adds where at the end. 

Is such scenario possible with existing api ?

**Comment by huandu** [comment]
Unfortunately, it's not possible to parse SQL with existing API right now. The `SQL()` method do nothing with the input.

However, back to your case, if you just want to reuse a piece of SQL, it's possible to write code like following. Remember, this package is only a string builder for SQL. You're free to use any part of it separately.

```go
yesterday := time.Now().Add(-24 * time.Hour).Unix()
sb := sqlbuilder.NewSelectBuilder()
sb.SQL("select name, address, phone from userinfo group by name")
sb.Where(
    sb.Equal("status", 1),
    sb.GTE("updated_at", yesterday),
)

sql, _ := sb.Build()
fmt.Println(sql)

// Output:
// select name, address, phone from userinfo group by name WHERE status = ? AND updated_at >= ?
```

You can run the code online: https://go.dev/play/p/2BOFyIG6AvU

**Comment by adeesh-vunet** [comment]
In my case, there will be exiting sql query in a file which has the GroupBY clause, I have to add the WHERE clause at runtime. 
Having GroupBY clause come before the WHERE is not valid sql query. This was my issue. 

Anyway, Got your answer. Thank you.

**Comment by Adeesh2411** [comment]
In my case having, I have sql queries where it already has GROUP BY clause, I have to add where clause at runtime based on user input. But if GROUP BY clause comes before WHERE, then it is not a valid sql query. This was my issue. 

Anyway Got your answer. Thank You

**Comment by huandu** [comment]
Ah, I overlooked the `GROUP BY`. If your case is to build `WHERE` clause, there is another option for you.

```go
pattern := "select name, address, phone from userinfo %v group by name"

yesterday := time.Now().Add(-24 * time.Hour).Unix()
sb := sqlbuilder.NewSelectBuilder()
sb.Where(
    sb.Equal("status", 1),
    sb.GTE("updated_at", yesterday),
)

builder := sqlbuilder.Buildf(pattern, sb)

sql, args := builder.Build()
fmt.Println(sql)
```

Here is the demo: https://go.dev/play/p/h-Z9YShWzW5
