### ISSUE TITLE
Support update returning syntax

### ISSUE THREAD

**Issue by yz89122** [huandu/go-sqlbuilder#142]
# Description

As title.

https://www.postgresql.org/docs/16/sql-update.html

## Example SQL

```SQL
UPDATE t SET c1 = $1 WHERE id = $2 RETURNING c2, c3;
UPDATE t SET c1 = $1 WHERE id = $2 RETURNING *;
```

**Comment by huandu** [comment]
This is a PostgreSQL/SQLite specific syntax and there are no simple implementation in other DB flavors. I don't think it's feasible to add an API for this syntax. My suggestion is to use `SQL()` method to add the returning yourself.
