### ISSUE TITLE
Light ORM struct on multiple table join columns

### ISSUE THREAD

**Issue by slok** [huandu/go-sqlbuilder#148]
Hi!

First of all, many thanks for this awesome library! :smile:

I have a question regarding light ORM and joined tables, I searched for an example but I didn't find anyting.

I would like to get columns from multiple tables using an inner join. Is there a way of using an ORM struct and map both tables to same struct object somwhow (using a tag or anything else)?

Example, I would like to do this:

```sql
SELECT
    m.serial, m.id, m.org_id, m.user_id, m.role_id, m.created_at,
    u.email, u.name
FROM membership m INNER JOIN user u ON m.user_id=u.id
WHERE m.org_id = 'xxxxxxxxxxxxxxxxxxx'
```
And having a similar struct like this, map it somehow:

```go
type sqlMember struct {
	// Membership table.
	MembershipID        string    `db:"id`
	OrgID               string    `db:"org_id"`
	UserID              string    `db:"user_id"`
	RoleID              string    `db:"role_id"`
	MembershipCreatedAt time.Time `db:"created_at"`
	 // User table.
	Name                string    `db:"name"`
	Email               string    `db:"email"`
}
```

Is this possible?

Thank you!

**Comment by huandu** [comment]
You can use `Struct` like following.

```go
type Member struct {
	// Membership table.
	MembershipID        string    `db:"m.id"`
	OrgID               string    `db:"m.org_id"`
	UserID              string    `db:"m.user_id"`
	RoleID              string    `db:"m.role_id"`
	MembershipCreatedAt time.Time `db:"m.created_at"`
	// User table.
	Name  string `db:"u.name"`
	Email string `db:"u.email"`
}

func main() {
	st := sqlbuilder.NewStruct(Member{})
	sb := st.SelectFrom("membership m").JoinWithOption(sqlbuilder.InnerJoin, "user u", "m.user_id = u.id")
	sb.Where(sb.Equal("m.org_id", "xxxxxxxx"))

	fmt.Println(sb)
	// Output:
	// SELECT m.id, m.org_id, m.user_id, m.role_id, m.created_at, u.name, u.email FROM membership m INNER JOIN user u ON m.user_id = u.id WHERE m.org_id = ?
}
```

After you get results from database, you can then use `st.Addr(&member)` with `rows.Scan()` to decode a row to an instance of `Member`.

Live demo: https://go.dev/play/p/sza5UQD-u7O

**Comment by slok** [comment]
Awesome! many thanks for the fast answer, I jsut tested and works perfectly!

I didn't know that adding the column prefix on the struct tag would override the default prefix.  Could we add this to the readme? So  anyone with the same doubts find it easily.

Many thanks one more time! :pray:

**Comment by huandu** [comment]
Sure. It's a good suggestion. Thanks.
