### ISSUE TITLE
生成sql 语句报错

### ISSUE THREAD

**Issue by yiyang1125** [huandu/go-sqlbuilder#152]
SELECT COUNT(*) AS total FROM (SELECT id, in_price, sale_price, validate_date, medical_id FROM (SELECT id, in_price, sale_price, validate_date, medical_id, ROW_NUMBER() OVER (PARTITION BY medical_id ORDER BY validate_date, id) AS row_num FROM in_items WHERE current > ?) AS t WHERE row_num = ?) AS t1 LEFT JOIN medical m ON m.id=t1.medical_id LEFT JOIN stocks s ON s.medical_id=t1.medical_id AND s.outpatient_id = ? WHERE (m.type IN (?) OR m.type1 IN (?)) [0 1 2 [中成药 中药饮片 中药颗粒] [针剂]]
2024/05/28 - 11:14:57.283	error	/Users/liyiyang/Documents/xinye/tangshan/server/service/inventory/stock.go:314	gernerate sql error	{"error": "go-sqlbuilder: unsupported args when interpolating"}

**Comment by yiyang1125** [comment]
我根据上述条件自己填进去， sql 语句在mysql 中可以执行。
SELECT COUNT(*) AS total 
FROM 
	(SELECT id, in_price, sale_price, validate_date, medical_id 
	 FROM (SELECT id, in_price, sale_price, validate_date, medical_id, 
	 		ROW_NUMBER() OVER (PARTITION BY medical_id ORDER BY validate_date, id) AS row_num FROM in_items WHERE current > 0) AS t 
	 		WHERE row_num = 1) AS t1 
LEFT JOIN medical m ON m.id=t1.medical_id 
LEFT JOIN stocks s ON s.medical_id=t1.medical_id AND s.outpatient_id = 2
WHERE (m.type IN ('中成药', '中药饮片' '中药颗粒') OR m.type1 IN ('针剂'))

**Comment by huandu** [comment]
同上，需要调用 Flatten 函数才行。

这样设计是为了防止不小心传错参数类型，导致隐藏的线上故障、增加调试成本。就像你现在遇到的问题一样，这个库会明确的阻止这种参数调用，而不是默默地在 IN 里面拼一个错误的字符串形式值而导致 SQL 无法获得结果。

**Comment by yiyang1125** [comment]
谢谢各位， 我加上后，依然报错，是 IN不支持字符串数组吗？	{"error": "go-sqlbuilder: unsupported args when interpolating"}
