### ISSUE TITLE
【Question】是否考虑支持 Dameng

### ISSUE THREAD

**Issue by jaronnie** [huandu/go-sqlbuilder#154]

**Comment by huandu** [comment]
可以，能提供一下 Dameng 与其他 SQL 系统的差异吗？如果差异不大我可以顺手就能开发，如果差异大的话，我得考虑下开发的时间。

**Comment by jaronnie** [comment]
目前简单的语法能够兼容 mysql, 后续我使用复杂语句遇到问题了，我再看看，然后提一个 pr吧

**Comment by huandu** [comment]
如果需要有定制 flavor 的必要，再提出来吧，我先关闭了。
