### ISSUE TITLE
怎么拼接json_contains()条件呢？

### ISSUE THREAD

**Issue by donnol** [huandu/go-sqlbuilder#155]
比如，我有以下语句：

```sql
select *
from order o
where json_contains(
	o.body->'$.List[*].Orders[*].Number', 
	json_quote('1110698485'), 
	'$'
);
```

其中，1110698485是传入的条件，这种语句怎么写好呢？

**Comment by huandu** [comment]
当前没有对 `json_contains` 提供直接的支持，你需要通过拼字符串来实现这个 SQL。假设 `1110698485` 是需要 escape 的数据，这条 SQL 可以这么写：

```go
sb := sqlbuilder.Select("*").From("order o")
sb.Where(
fmt.Sprintf(
	`json_contains(
o.body->'$.List[*].Orders[*].Number', 
json_quote(%s), 
'$'
)`, sb.Var(1110698485)))

sql, args := sb.Build()
println(sql)
println(args)
// Output:
// SELECT * FROM order o WHERE json_contains(
//   o.body->'$.List[*].Orders[*].Number', 
//   json_quote(?), 
//   '$'
// )
// [1110698485]
```

**Comment by donnol** [comment]
好的。

另外，我看现在的Equal等方法都是在Cond结构上的，有没有可能做成函数的形式，方便用户自定义呢？

**Comment by huandu** [comment]
现在已经可以做到比较方便的自定义了，推荐这么做：封装一个自己的函数，将 `*Cond` 作为参数传入，再加上其他必要参数即可，由于这个库本质上就是在拼字符串，所以你只需要按需拼字符串即可实现各种 FUNCTION。

这是一个[可运行的例子](https://go.dev/play/p/YE53eB2oJH_Q)，封装了 `JSON_CONTAINS` 和 `JSON_QUOTE`，你可以根据需求做的更加复杂一些，支持更多更复杂的参数类型等。

**Comment by donnol** [comment]
好的，多谢。
