### ISSUE TITLE
优化struct对join的支持

### ISSUE THREAD

**Issue by Sora233** [huandu/go-sqlbuilder#164]
现在struct如果有join并不是很灵活，一些方面：
- Select()不能增加字段
- join的字段如果在struct里面，不能默认without
- 一些有多个struct的情况

**Comment by huandu** [comment]
@Sora233 可以补充一下更多信息吗，这样我能明白你期望的功能是什么。多谢。

**Comment by huandu** [comment]
我在最新版本里面给 `SelectBuilder` 增加了 `SelectMore` 方法，可以实现追加更多的字段到 SELECT 里面。

**Comment by huandu** [comment]
由于长期没有反馈，先关闭这个问题。
