### ISSUE TITLE
[QA] 怎么追加一段原始的sql和args

### ISSUE THREAD

**Issue by Tang-RoseChild** [huandu/go-sqlbuilder#165]
创建 update builder
```
builder := sqlbuilder.NewUpdateBuilder()
builder.Update(AdminOperationLog{}.Table())
// ... 其他set语句
```

自定义方法生成原始的 sql 和 args
```
rsql, rargs := custom.BuildWhere()

rsql,rargs 是原始的sql 和参数, 
例如 
rsql:
where a =? and b =?
rags:
[1,2]
```
怎么将原始的 sql 和 args, 插入到 builder 中呢?

**Comment by huandu** [comment]
不太明白你希望做到什么效果，还希望能说的更明确些。我理解，你是想复用 `BuildWhere()` 的返回结果，如果是这样的话，在这个库里面推荐的做法是生成 `Builder` 实例并且在其他 `Builder` 里面使用。

例如，如果要复用 `WHERE`，你可以参考 [`WhereClause` 在多个 `Builder` 中复用的例子](https://pkg.go.dev/github.com/huandu/go-sqlbuilder#example-WhereClause-SharedAmongBuilders)，看看是否跟你的场景比较像。

**Comment by huandu** [comment]
@Tang-RoseChild 可以补充一下信息吗？不知道我上面的回答是否对你有帮助呢？

**Comment by antyiwei** [comment]
Interpolate args in the sql

事例不够直观：

sb := MySQL.NewSelectBuilder()

应该改为

sb := sqlbuilder.MySQL.NewSelectBuilder()

**Comment by huandu** [comment]
@antyiwei 没太明白，你是想指出什么问题，是否跟这个 issue 本身有关呢？

**Comment by huandu** [comment]
由于长期没有反馈，先关闭这个问题。
