### ISSUE TITLE
Can we use struct for nested SQL of insert too?

### ISSUE THREAD

**Issue by wangmir** [huandu/go-sqlbuilder#182]
I wanna insert data using struct, and then select query for stored data (but I'm using View, so I will do select query into view rather than table). 

From the doc, I cannot find the way to handle this with using struct. Struct returns insert builder, and insert builder can support nested select query, but I cannot use struct for that select query.

So, do we have method to nest separately created select builder with struct as a select builder inside of insert builder based on the struct again.

**Comment by huandu** [comment]
You can try to call `Struct.Columns()` to get a slice of column names and use them in `InsertBuilder.Select()`.

Here is a simple sample for you.

```go
var fooStruct = sqlbuilder.NewStruct(Foo{})
fooStruct.InsertInto("foo").Select(fooStruct.Columns()...)
```

**Comment by wangmir** [comment]
Thanks!
