### ISSUE TITLE
UpdateBuilder generator with CTE

### ISSUE THREAD

**Issue by arslanovdi** [huandu/go-sqlbuilder#184]
> @Sora233 我实现了一下相关逻辑，请帮忙看看 #179 吧，主要看一下 `cte_test.go` 里面新加的两个 example 函数，看是否生成的 SQL 符合预期，我怕生成的 PostgreSQL 语句有误。感谢。

Hello! For PostgreSQL it generates incorrectly
Your example: 
`// WITH users (user_id) AS (SELECT user_id FROM vip_users) UPDATE orders FROM users SET orders.transport_fee = 0 WHERE users.user_id = orders.user_id`

It should be:
`// WITH users (user_id) AS (SELECT user_id FROM vip_users) UPDATE orders SET transport_fee = 0 FROM users WHERE users.user_id = orders.user_id`

_Originally posted by @arslanovdi in https://github.com/huandu/go-sqlbuilder/issues/176#issuecomment-2515433362_

**Comment by huandu** [comment]
Thanks for raising this issue to me. Fixed in tag v1.33.1.
