### ISSUE TITLE
Equal Does Not Work With Column Names

### ISSUE THREAD

**Issue by califlower** [huandu/go-sqlbuilder#25]
sb.Equal doesn't work with column names because it tries to set the column as a string. Needs a new equal function for column names that doesn't get embedded as an arg

example 

sb.Equal(tableB.id=tableA.question_id) would fail silently

**Comment by huandu** [comment]
The second arg `value interface{}` is designed for argument which should be escaped.

You can either do this

```go
sb.Equal("tableB.id", sqlbuilder.Raw("tableA.question_id"))
```

or that

```go
sb.Where("tableB.id=tableA.question_id") // Yes. I recommend you to use plain text in this case.
```

to solve your problem.

**Comment by huandu** [comment]
Feel free to reopen this issue if you still have any question.
