### ISSUE TITLE
Update of non omitempty pointer field with nil value panics

### ISSUE THREAD

**Issue by scheca** [huandu/go-sqlbuilder#27]
Given a pointer field in a `Struct`, and a value update missing that field, there's an extra call to `dereferencedValue` in `UpdateForTag` which returns an invalid `Value`. Avoiding this call for non-omitempty fields with empty values would prevent that nil-pointer access in reflection:

```go
		if isEmptyValue(val) {
			if _, ok := s.omitEmptyFields[f]; ok {
				continue
			}
		} else {
			val = dereferencedValue(val)
		}
		data := val.Interface()
		assignments = append(assignments, ub.Assign(quoted[i], data))
```

I have a local branch but wasn't able to open a PR. If you think it may be worth a review, please let me know how I can open it and upload the code.

This is the test case I've added to `struct_test.go` to work on this:

```go
type structWithPointers struct {
	A int      `db:"aa" fieldopt:"omitempty"`
	B *string  `db:"bb"`
	C *float64 `db:"cc" fieldopt:"omitempty"`
}

func TestStructWithPointers(t *testing.T) {
	st := NewStruct(new(structWithPointers)).For(MySQL)
	sql1, _ := st.Update("foo", new(structWithPointers)).Build()

	if expected := "UPDATE foo SET bb = ?"; sql1 != expected {
		t.Fatalf("invalid sql. [expected:%v] [actual:%v]", expected, sql1)
	}

	a := 123
	c := 123.45
	sql2, args2 := st.Update("foo", &structWithPointers{
		A: a,
		C: &c,
	}).Build()

	if expected := "UPDATE foo SET aa = ?, bb = ?, cc = ?"; sql2 != expected {
		t.Fatalf("invalid sql. [expected:%v] [actual:%v]", expected, sql2)
	}

	if expected := []interface{}{a, (*string)(nil), c}; !reflect.DeepEqual(expected, args2) {
		t.Fatalf("invalid args. [expected:%#v] [actual:%#v]", expected, args2)
	}
}```

**Comment by huandu** [comment]
Cool. Thanks for raising this bug.

Regarding to how to send PR, you need to fork this project, create a branch in your forked project, update code and push to your forked project. After your commit is pushed, you can see a green button on the very beginning of the front page of your forked project. Try it.

**Comment by scheca** [comment]
Thank you for the quick feedback. I've followed the forking and got this [PR](https://github.com/huandu/go-sqlbuilder/pull/28) created in this repo.

**Comment by scheca** [comment]
Thanks for the quick release of 1.4.1, and congrats for the library 👍
