### ISSUE TITLE
Cannot using .Like in Where

### ISSUE THREAD

**Issue by TangMonk** [huandu/go-sqlbuilder#31]
```
sb.Select("*").From("articles").OrderBy("created_at desc").Where(
  sb.Like("title", "%a%"),
)
```

error shows:

```
not enough args to execute query: want 1 got 0
```

**Comment by huandu** [comment]
I cannot reproduce your issue.

Following code works as expected.

```go
func ExampleSelectBuilder_like() {
	sb := NewSelectBuilder()
	sb.Select("*").From("articles").OrderBy("created_at desc").Where(
		sb.Like("title", "%a%"),
	)
	query, args := sb.Build()
	fmt.Println(query)
	fmt.Println(args)

	// Output:
	// SELECT * FROM articles WHERE title LIKE ? ORDER BY created_at desc
	// [%a%]
}
```

**Comment by huandu** [comment]
The error message "not enough args to execute query: want 1 got 0" is returned by methods implemented in `database/sql`. I guess you forgot to provide `args` when calling `Query` or `Exec` or other similar methods. It's not a bug in this package. It's a bug in your business code.

**Comment by huandu** [comment]
If you still have any question, feel free to comment on this issue.
