### ISSUE TITLE
why are select, order by, and group by $ escaped

### ISSUE THREAD

**Issue by dvic** [huandu/go-sqlbuilder#35]
Is there any particular reason for this? Is there a workaround to use sub-expressions with positional arguments ($1, $2, etc. obtained using `.Var()`) in these positions?

**Comment by huandu** [comment]
This package uses `$0 .. $n` to represent placeholders. If the `$` is not escaped in `Select`/`OrderBy`/etc, there will be some unexpected behavior when building SQL.

Why do you need to use `$1`/`$2` explicitly? Please let me know your scenario. I can help you.

**Comment by dvic** [comment]
I lost an hour or so on this issue because `.Build()` was missing arguments supplied in `sb.Var` (I used sub-expressions that used positional arguments in the select and order by). This is not what you expect, you expect when you call `.Var()` on a builder that the variable is always returned in `.Build()` not matter what, right?

**Comment by huandu** [comment]
Can you please show me some code? I still don't get your point.

**Comment by dvic** [comment]
Or a more realistic example, where I want to find users with 'foo' in their name but sort the users whose name starts with 'foo' first:

```go
	sqlbuilder.DefaultFlavor = sqlbuilder.PostgreSQL
	sb := sqlbuilder.NewSelectBuilder()

	foo := sb.Var("foo")
	sb.Select("id")
	sb.From("user")
	sb.Where("name ~* " + foo)
	sb.OrderBy(fmt.Sprintf("name ~* '^' || %s DESC", foo)) // DESC here because BOOL is sorted FALSE, TRUE

	sql, args := sb.Build()
	fmt.Println(sql)
	fmt.Println(args)
```

Prints
```
SELECT id FROM user WHERE name ~* $1 ORDER BY name ~* '^' || $0 DESC
[foo]
```

I understand now why this happens, but it's not desired I think, not sure how to fix this without introducing breaking changes.

**Comment by huandu** [comment]
OK. I get it. I wasn't aware of your use cases. I can fix it soon.
