### ISSUE TITLE
Struct SelectFrom should include full table name

### ISSUE THREAD

**Issue by albertorestifo** [huandu/go-sqlbuilder#40]
When making joins, it would be useful is the `Struct` added the table name to the fields or if it implemented a `SelectFromAs` method.

Right now, for example, there is no way of doing this:

```go
var c Company
sb := companyStruct.SelectFrom("companies", &c)
sb.Join("company_balances", "company_balances.company_id = companies.company_id").
	Where(sb.E("balance_id", balanceID)).
	Limit(1)
```

This will fail as both the `companies` and `company_balances` table have a `company_id` field.

**Comment by albertorestifo** [comment]
I'm willing to make a PR to help with this as it's important for our use-case.

Which approach do you prefer?

1. Add a `SelectFromAs` to the `Struct`
2. Always prefix the fields with the table name

I would personally go with 2, as it can be applied to all queries in the generator and it won't break existing queries

**Comment by huandu** [comment]
Thanks for your suggestion, @albertorestifo. I'm thinking of how to design it these days. The ideal solution in my mind is similar to 2 except that the prefix is added only if JOIN is used in `sb`. It's not easy to implement it in this way without magic. That's why I'm still thinking of it.

**Comment by huandu** [comment]
The commit fb2186e implements solution 2. I still cannot find a way to add prefix only if JOIN is used without ugly magic. Let's go with solution 2 before we have a perfect solution.

**Comment by albertorestifo** [comment]
This worked perfectly, many thanks for the speedy solution
