### ISSUE TITLE
support OR boolean operator in where clause

### ISSUE THREAD

**Issue by WangBeyond** [huandu/go-sqlbuilder#43]
Seemly this library only supports appending AND expression to where clause, is it possible to support OR operator?

**Comment by huandu** [comment]
There is an OR operator. See [Cond.Or](https://godoc.org/github.com/huandu/go-sqlbuilder#Cond.Or). It can be used in `SelectBuilder`, `UpdateBuilder` and `DeleteBuilder`.

**Comment by WangBeyond** [comment]
Is there anyway to do nested where clause?

For example (exprA or exprB) and (exprC or exprB)

**Comment by huandu** [comment]
Yes. It's simple. See [this sample](https://godoc.org/github.com/huandu/go-sqlbuilder#example-SelectBuilder).

```go
sb := NewSelectBuilder()
sb.Distinct().Select("id", "name", sb.As("COUNT(*)", "t"))
sb.From("demo.user")
sb.Where(
    sb.Or(
        exprA,
        exprB,
    ),
    sb.Or(
        exprC,
        exprD,
    ),
)
```
