### ISSUE TITLE
Why using sql builder like squirrel or go-sqlbuilder rather than plain old sql string?

### ISSUE THREAD

**Issue by liudongqing** [huandu/go-sqlbuilder#45]
just starting to use golang in production and found some legacy code using sqlbuilder heavily. I found the code is very hard to understand compared to the sql string.

sb := sqlbuilder.NewSelectBuilder()

sb.Select("id", "name", sb.As("COUNT(*)", "c"))
sb.From("user")
sb.Where(sb.In("status", 1, 2, 5))
vs

sql:=`SELECT id, name, COUNT(*) AS c FROM user WHERE status IN (?, ?, ?)`

I think the second one is much easy to understand.

**Comment by huandu** [comment]
Feel free to abandon it in your production code and use plain SQL string directly if you prefer.

A SQL builder, this package or other similar package, is a kind of trade-off to leverage readability and correctness. It's always OK to use plain SQL string in production code. The only issue is that developers may misspell some words in SQL or forget to escape some sensitive strings unconsciously. A SQL builder can help us in these scenarios.

Besides SQL builders, there are lots of other approaches for these scenarios, e.g. MyBatis-like SQL template strings or ORMs. There is no so-called best approach. Find the best approach you like most and use it. That's it.

**Comment by liudongqing** [comment]
Got it, Thank you for the quick and informative response！
