### ISSUE TITLE
能不能增加 union 的 api ？

### ISSUE THREAD

**Issue by WilliamYang1992** [huandu/go-sqlbuilder#47]

**Comment by WilliamYang1992** [comment]
如果可以的话，希望加上union，union_all 功能，谢谢！

**Comment by huandu** [comment]
计划增加新的方法 `func Union(keyword UnionKeyword, left, right *SelectBuilder) *SelectBuilder`，看起来这个语法有点麻烦，可能在实现的时候还会调整接口细节。

**Comment by WilliamYang1992** [comment]
感谢你的回复，看起来还可以，期望快一点更新😊
