### ISSUE TITLE
Plan about support SQLite3

### ISSUE THREAD

**Issue by vit1251** [huandu/go-sqlbuilder#51]
Could you please clarify plans about SQLite3 support?

**Comment by huandu** [comment]
I have no plan until anyone asks for it. Ah, here is one.

**Comment by huandu** [comment]
I did some investigation on SQLite3 SQL syntax. I find that it seems the same syntax as MySQL. I suppose you are a SQLite3 user. Can you please let me know what's the SQLite3-only syntax and what should I change in this package?

@vit1251

**Comment by vit1251** [comment]
@huandu I think that dialect does not have some aspects and provide another one column escape char. Actually without using your builder I does not know what diufferent but I does not want to use MySQL driver instead.

**Comment by huandu** [comment]
If I simply add a flavor const named SQLite just as a dialect of MySQL, is it OK?

**Comment by vit1251** [comment]
@huandu at the start that OK but you should wait for report about differences with this one little later.
