### ISSUE TITLE
Is it possible to call stored procedure

### ISSUE THREAD

**Issue by smartaquarius10** [huandu/go-sqlbuilder#52]
Hello,

Is it possible to call stored procedures from this. We can call functions as it can be called as part of select query. 

But any chance for stored procedures. If yes, can you share any sample code. 

Thank you

**Comment by huandu** [comment]
Yes. You can use `Build`/`Buildf`/`BuildNamed` to build whatever SQL you need.

```go
proc := sqlbuilder.Build(`CREATE PROCEDURE database.foo() 
SELECT * FROM foo;`)
call := sqlbuilder.Build("CALL database.foo()")

// Create proc.
sql, args := proc.Build()
db.Exec(sql, args...)

// Call proc.
sql, args = call.Build()
db.Exec(sql, args...)
```
