### ISSUE TITLE
Support for `FOR UPDATE` or `IN SHARE MODE` in `SELECT` clause

### ISSUE THREAD

**Issue by wangggong** [huandu/go-sqlbuilder#53]
RT.

Maybe we can support these two clause in SELECT statement?

**Comment by YiuTerran** [comment]
After call `Build`, you can add ` for update` at the tail.

**Comment by wangggong** [comment]
Of course we can, in fact this method is used now in our project; but it is also stitching the SQL query statement. If it is allowed, SQL injection cannot be avoided.

**Comment by huandu** [comment]
Oops. I overlooked this thread for quite a long time. Let me think of a way to support this. Maybe I can simply add some new methods for these clauses.

**Comment by huandu** [comment]
It's fixed by #58.
