### ISSUE TITLE
Add INNER as a JoinOption

### ISSUE THREAD

**Issue by rw-access** [huandu/go-sqlbuilder#56]
I've run into a use case that could be made simpler with another `JoinOption` available.

I'm dynamically generating SQL queries and conditionally change from `JOIN` to `LEFT JOIN`. Since an unmodified `JOIN` is equivalent to `INNER JOIN` then I realized that I could use `JoinWithOption`, and conditionally change the `JoinOption`.

There are a few obvious options Ito do this:
* Conditionally call either `Join` or `JoinWIthOption`, with a JoinOption to the second
* Create my own const JoinOption that's just the word "INNER". Then I'll conditionally just use a package constant `Inner` or the imported constant `sqlbuilder.LeftJoin`. It's a little inconsistent, but not bad
* Add a new `const Inner JoinOption = "INNER"` to the library

Any thoughts on the last option? I figured it's an easy and reasonable addition.
I can create a PR if you think it's a good path forward for the library.

**Comment by huandu** [comment]
I agree. Adding a new const `InnerJoin` can improve readability. Please submit a PR for it. Welcome to contribute.

**Comment by rw-access** [comment]
Will do.
I just recently started with this library and I'm enjoying it. Thanks!

**Comment by huandu** [comment]
👍
