### ISSUE TITLE
PostgreSQL 参数占位符用法

### ISSUE THREAD

**Issue by panjunjie** [huandu/go-sqlbuilder#6]
PostgreSQL 参数的占位符，一般都是 $1...$6... ，而 go-sqlbuilder 生成的 sql 语句是 ?...?... ，这个是有特别的用法，没有在文档里说明吗？

**Comment by huandu** [comment]
这个是 mysql 的用法。

我看了下 [pg 的 driver](https://godoc.org/github.com/lib/pq)，确实只支持 `$1...$n` 这样的 placeholder，看起来或许应该支持一下定制下这样的需求，我来考虑一下。

**Comment by huandu** [comment]
已经通过 `Flavor` 机制支持 `PostgreSQL`，可以用以下方法使用：

* 将 `DefaultFlavor` 设置为 `PostgreSQL`，这样所有 builder 都使用 `PostgreSQL` 风格的 marker；
* 使用 `PostgreSQL.NewSelectBuilder()` 等函数创建 builder；
* 使用 `SelectBuilder` 的 `SetFlavor(flavor)` 方法，所有的 builder 都支持这个方法；
* 使用 `Builder` 接口的 `BuildWithFlavor(flavor)` 方法，在 build 的时候指定 flavor。
