### ISSUE TITLE
ORDER BY statement bug

### ISSUE THREAD

**Issue by Morainy** [huandu/go-sqlbuilder#62]
when I use this:
`builder.OrderBy("up_ts", "task_id").Desc()`
will generate 
`ORDER BY up_ts task_id DESC`
but I want:
`ORDER BY up_ts DESC task_id DESC`

**Comment by huandu** [comment]
This is a by-design feature, not a bug. This topic was discussed in the past. See #24 for details.

**Comment by huandu** [comment]
Close it due to no response for 1 week. Feel free to re-open it if you have more questions. @Morainy
