### ISSUE TITLE
How to model WITH queries

### ISSUE THREAD

**Issue by altitude** [huandu/go-sqlbuilder#63]
Hey @huandu,

First, thanks so much for this repo, helped me tremendously to streamline my code to something more readable and manageable.

One thing I'm wondering how to migrate to sqlbuilder is queries using WITH pseudo tables, e.g.

```SQL
WITH food AS (
  SELECT * FROM fruits
  UNION
  SELECT * FROM vegetables
)
SELECT avg(price)
FROM food;
```

Thanks for your help :)

**Comment by huandu** [comment]
My recommendation is to write a function like this.

```go
func With(name string, dataset sqlbuilder.Builder, sel *sqlbuilder.SelectBuilder) sqlbuilder.Builder {
    sel.From(name) // overwrite FROM.
    return sqlbuilder.Build("WITH $? AS ($?) $?", name, dataset, sel)
}
```

Then, you can call `With` like following.

```go
sb1 := sqlbuilder.Select("*").From("fruits")
sb2 := sqlbuilder.Select("*").From("vegetables")
sb3 := sqlbuilder.Select("avg(price)").From("food")

// Build full SQL.
sql, _ := With("food", sqlbuilder.Union(sb1, sb2), sb3).Build()
```

**Comment by altitude** [comment]
Amazing, I understand. Just tried it, works great and pretty readable. Thanks for your help :)

PS: Would love to sponsor the project if there's a way to make it work.

**Comment by huandu** [comment]
Edited my previous comment for function `With`.

```go
func With(name string, dataset sqlbuilder.Builder, sel *sqlbuilder.SelectBuilder) sqlbuilder.Builder {
    sel.From(name) // overwrite FROM.
    return sqlbuilder.Build("WITH $? AS ($?) $?", sqlbuilder.Raw(name), dataset, sel)
}
```

I use `sqlbuilder.Raw(name)` to make sure that the `name` will be considered as a literal string.

P.S. Thanks for your offer. I'll think of it.
