### ISSUE TITLE
SQL Server flavor

### ISSUE THREAD

**Issue by MagnifiGo** [huandu/go-sqlbuilder#64]
Hello,

This is a very interesting project, thank you for  publishing @huandu !

> Right now, there are only three flavors, MySQL, PostgreSQL and SQLite. Open new issue to me to ask for a new flavor if you find it necessary.

Any chance you could add [SQL Server](https://db-engines.com/en/system/Microsoft+SQL+Server) support ? If **go-sqlbuilder** supports [the 2nd, 4th and 9th](https://db-engines.com/en/ranking) RDBMS by rank, why not [the 3rd](https://db-engines.com/en/system/Microsoft+SQL+Server) as well? I believe this will increase project adoption by enterprise developers.

**Comment by huandu** [comment]
Sure. I can add a new flavor per your request.

I'm not familiar with SQL Server. Can you help me to review my code? I'll create a new branch for this feature.

**Comment by MagnifiGo** [comment]
@huandu sure.

**Comment by huandu** [comment]
Hi @MagnifiGo , I submitted a PR #66 to fix this issue. As far as I know, the major SQL syntax differences between SQL Server and other DBMS are LIMIT and OFFSET. Please help me to check whether there is anything that I'm missing.

**Comment by MagnifiGo** [comment]
Hi @huandu . Thank you for acting so fast. I will bank some time to look into #66 sometime this week and keep you posted. I hope that's okay with you.
