### ISSUE TITLE
What is required to add ClickHouse support?

### ISSUE THREAD

**Issue by marwan-nwh** [huandu/go-sqlbuilder#70]
Hi,

I want to add ClickHouse support to this, but not sure that is required to add a new database.
I hope I can get some tips, then I would love to make a PR for it.

Thanks

**Comment by huandu** [comment]
To add a new SQL dialect (I call it "flavor") you need to add a new flavor const in `flavor.go` and add necessary code in related builders. Many SQL flavors are similar, just like MySQL and SQLite. You can search keyword `SQLite` in code, and then you can understand how to add a similar dialect.
