### ISSUE TITLE
Only the last `GroupBy()` call will be used

### ISSUE THREAD

**Issue by ionling** [huandu/go-sqlbuilder#74]
When you call `GroupBy()` multiple times, only the last one will be in the SQL.

Code:
```go
func (sb *SelectBuilder) GroupBy(col ...string) *SelectBuilder {
	sb.groupByCols = col
	sb.marker = selectMarkerAfterGroupBy
	return sb
}
```

Why not:
```go
func (sb *SelectBuilder) GroupBy(col ...string) *SelectBuilder {
	sb.groupByCols = append(sb.groupByCols, col...)
	sb.marker = selectMarkerAfterGroupBy
	return sb
}
```

**Comment by huandu** [comment]
Current API design enables us to update `GROUP BY` columns more than once. If we want to append more columns, we can simply append data to a `cols` slice and then call `GroupBy(cols...)`.

**Comment by ionling** [comment]
The `Where()` method support multiple times calling, and I think we can keep the behavior of `Where()` and `GroupBy()` consistent. That will be better and convenient other than use `append()` function.
