### ISSUE TITLE
希望添加对struct columns和values的单独导出功能

### ISSUE THREAD

**Issue by Sora233** [huandu/go-sqlbuilder#75]
例如：
struct.StructColumnsForTag("table", "tag") -> []string，返回在build语句中会使用的column names
struct.StructValuesForTag("table", "tag", values...) -> [][]interface{}，返回columns对应的values

场景是我在配合 [sqlmock](https://github.com/DATA-DOG/go-sqlmock) 使用的时候有些困难，目前需要手动实现一遍struct内的反射逻辑

**Comment by huandu** [comment]
我能明白 column names 这个需求，不过第二条里面说的 values 是什么意思呀，麻烦给一些案例我来理解一下。

**Comment by Sora233** [comment]
简单来说我希望能mock`sql.Rows`，我上面提到的库能够实现这个，而问题是我在mock时需要设置两个东西，一个是`Rows.Columns()`，这个对应我的第一个需求；另外一个是`Rows.Scan`，当我使用`Struct.Addr`的时候，我需要巧妙地调整`Rows Values`的类型、顺序等，让它刚好满足`Struct.Addr`的要求（因为Addr返回的是地址，我目前可以把addr的结果解引用一遍）。
我希望能够通过`Struct`生成这两个
