### ISSUE TITLE
reflect.StructField.IsExported only support go 1.17 or above

### ISSUE THREAD

**Issue by ranhaoliuLeo** [huandu/go-sqlbuilder#76]
I was using sqlbuilder 1.14.0 in project. My golang version of env is 1.16 and can not build project because  the `IsExported` using in the sqlbuilder pkg. Should upgrade go.mod file in sqlbuilder 1.14.0

**Comment by huandu** [comment]
The implementation of `IsExported` is extremely simple -- just check `f.PkgPath == ""`. It's not worth to drop go1.16 support for this method. I'll fix it as a bug.

**Comment by huandu** [comment]
Fix it in 20e19b9.
