### ISSUE TITLE
Improved SQL alias support on columns

### ISSUE THREAD

**Issue by danielnitsche** [huandu/go-sqlbuilder#78]
I have the use-case where I need to alias column names. I'm currently doing this:

```
type Report struct {
    First string `db:"FIRST_NAME as \"First\""'`
    Last string `db:"LAST_NAME as \"Last\""'`
}
```

This works, but if feels like a hack?

Assuming this is something you'd want to add to the library, would you recommend the above, or should we look at something like a new [fieldopt](https://github.com/huandu/go-sqlbuilder/blob/cbddc982df3ebd3f494a46d92d3a2d4a0595bc0b/structfields.go#L112)

**Comment by danielnitsche** [comment]
Thanks for the quick response!

I want to export to a CSV direct from PostgreSQL, so something like:
```
COPY (select column_a as A, column_b as B from some_table) TO '/tmp/some_file.csv' (format CSV, HEADER);
```

https://www.postgresql.org/docs/current/sql-copy.html

Using the `HEADER` option, the names of the column will be added as the first row of the CSV. I'd like to be able to control those names (more specifically, end-users will be downloading these generated CSV files, and so the field names need to be as understandable as possible). `fieldtag` / `usetag` is already helping me a lot because for one set of fields I can easily turn particular fields on/off.

**Comment by huandu** [comment]
It makes sense to me. I'll add a new struct field named `fieldas` to enable us to set alias name.

Here is a quick sample.

```go
type T struct {
    ColumnA string `db:"column_a" fieldas:"A"`
}

var t = NewStruct(new(T))
sb := t.SelectFrom("some_table")
builder := Build("COPY ($?) TO '/path/to/file.csv' (FORMAT CSV, HEADER)")
sql, _ := builder.Build()
print(sql)

// Output:
// COPY (SELECT column_a AS A FROM some_table) TO '/path/to/file.csv' (FORMAT CSV, HEADER)
```

Feel free to share your thoughts on this design.

**Comment by danielnitsche** [comment]
That sounds great to me 👍

One consideration I suppose is how you handle duplicate aliases. I noticed there was some code to check for duplicates so that may need to be extended?

**Comment by huandu** [comment]
If two struct fields have the same name defined by `db` tag, only the first field will be parsed and used. This is the only checks for duplication in `Struct` right now.

There is no special checks for the new `fieldas` tag so far in my mind. If you have any requirement on this part, feel free to let me know.

**Comment by huandu** [comment]
I'll merge #79 by the end of tomorrow, if there is no more feedback. Just FYI @danielnitsche

**Comment by danielnitsche** [comment]
Looks great thanks!
