### ISSUE TITLE
Problem when using with InfluxDB.

### ISSUE THREAD

**Issue by YiuTerran** [huandu/go-sqlbuilder#84]
When I use this lib to generate SQL for InfluxDB, I found it works good, except for that: I can't get the plain SQL.

Today, many databases are using SQL-Like DSL like InfluxDB, but they are using REST API, which needs plain SQL but not `?` placeholder and a parameter list.

I think that a method to generate plain SQL is much helpful.

**Comment by huandu** [comment]
You can [interpolate `args` in the generated `sql`](https://pkg.go.dev/github.com/huandu/go-sqlbuilder#readme-interpolate-args-in-the-sql). In your case, if you're using flavor `MySQL`, you can call `sqlbuilder.MySQL.Interpolate(sql, args)` to get a plain SQL without `?`.

**Comment by YiuTerran** [comment]
Oh, thanks, that is helpful~
