### ISSUE TITLE
Ilike condition

### ISSUE THREAD

**Issue by deivid11** [huandu/go-sqlbuilder#89]
Hello,
I'm using the like function of the selectBuilder to filter my results

```go
	builder.Where(builder.Like("names", "%"+*queryParams.Names+"%"))
```

I want the condition to be case insensitive, so I found 'ilike' function on postgres. I see the condition is not implemented, ¿is there a way to implement my own filter conditions?

**Comment by huandu** [comment]
The `Where()` method accepts any valid SQL string as input, so you can simply write your SQL like following.

```go
builder.Where(
    "names ilike " + builder.Var("%"+queryParams.Names+"%")
)
```

**Comment by deivid11** [comment]
Thanks @huandu!
