### ISSUE TITLE
Why update method using flavor not replace with $ ?

### ISSUE THREAD

**Issue by restuwahyu13** [huandu/go-sqlbuilder#93]
Hi @huandu, why i'm using flavor for update method is not work for query builder example 1, because this flavor not replace all `?` in query update to `$`.

#### UPDATE BUILDER 1
```go
psql := sqlb.PostgreSQL
query := psql.NewUpdateBuilder().Update("todos").Set("name = ?", "category = ?", "description = ?").Where("id = ?").String()

fmt.Println(query) // UPDATE todos SET name = ?, category = ?, description = ? WHERE id = ?
```

#### UPDATE BUILDER 2
```go
psql := sqlb.PostgreSQL
query := psql.NewUpdateBuilder().Update("todos")
query.Set(query.Equal("name", "?"), query.Equal("category", "?"), query.Equal("description", "?")).Where(query.Equal("id", "?")).String()

fmt.Println(query) //UPDATE todos SET name = $1, category = $2, description = $3 WHERE id = $4
```

**Comment by huandu** [comment]
Builders in this package don't parse any SQL. The `UpdateBuilder` isn't aware of the syntax of `name = ?`. There is no feature to automatically convert `?` to some other placeholders.

**Comment by huandu** [comment]
If you have more comments on this issue, feel free to leave comments and/or reopen this issue.
