### ISSUE TITLE
Benchmarks against  Masterminds/squirrel

### ISSUE THREAD

**Issue by yogibaba** [huandu/go-sqlbuilder#94]
Can we have benchmarks against other builder like [squirrel](https://github.com/Masterminds/squirrel)

**Comment by huandu** [comment]
Sure.

Besides squirrel, can you suggest more packages and typical SQL structures for comparison? It will be very helpful.

**Comment by yogibaba** [comment]
- [squirrel](https://github.com/Masterminds/squirrel)

Considering the builder for below;
- [sqlboiler](https://github.com/volatiletech/sqlboiler)
- [bun](https://github.com/uptrace/bun)

**Comment by huandu** [comment]
Got it. I'll investigate these packages and find a way to implement benchmark properly. I plan to finish the benchmark by the end of Jan.

**Comment by huandu** [comment]
@yogibaba I wrote some cases in #95. If you can help me to add more valuable cases, it's highly appreciated. Thanks.

**Comment by yogibaba** [comment]
To start with benchmark results against one package this is good. 
I will add some more in my free time and raise a PR.

**Comment by stephenafamo** [comment]
I have a benchmark repository for SQL Builders and I've added this package to it.

Check it out: <https://github.com/stephenafamo/go-sql-builder-benchmarks>

**Comment by huandu** [comment]
Thanks for your effort! I see go-sqlbuilder has outstanding performance results in your cases. That's cool. @stephenafamo
