### ISSUE TITLE
Plan to add a new flavor: Presto SQL

### ISSUE THREAD

**Issue by doyonghoon** [huandu/go-sqlbuilder#98]
I am not sure if it would be an excessive demand, but I found that it will be a sole-choice for me to use in my project if Presto SQL is supported. Thanks!

**Comment by tengteng22** [comment]
> From my observation, Presto SQL is the same as MySQL SQL syntax except following. Correct me if I'm wrong.
> 
> * Presto uses `LIMIT n OFFSET m` whereas MySQL uses `LIMIT n, m`;
> * Presto uses `from_hex('abcdef')` to create binary data whereas MySQL uses `0xabcdef` to do so.
> 
> I can implement new Presto flavor in this weekend if above is all I need to do.

From prestoDB [doc](https://prestodb.io/docs/current/sql/select.html) I think OFFSET goes before LIMIT.
This caused issue when I use this library to build a SQL query against AWS Athena (which is Presto SQL):
`mismatched input 'OFFSET'. Expecting: <EOF>`
